# Generated by Django 4.0.4 on 2022-05-15 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='photo', upload_to='photos'),
            preserve_default=False,
        ),
    ]
